# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2
# Declare the circleCI jobs
jobs:
  build:
    docker:
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/node:8.9.3

    working_directory: ~/tmp/racedale

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run test

  # deploy:
  #   docker:
  #     - image: google/cloud-sdk
  #   working_directory: ~/tmp/racedale
  #   steps:
  #     - run: echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
  # commands:
  #     - aws s3 sync jekyll/_site/docs s3://circle-production-static-site/docs/ --delete


# Declare how workflows
workflows:
    version: 2
    test-deploy:
      jobs:
        - build
        - deploy:
            requires:
              - build
            filters:
              branches:
                only: master


