/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import type {
  FileRoutesByPath,
  CreateServerFileRoute,
} from '@tanstack/react-start/server'
import {
  createServerRoute,
  createServerFileRoute,
} from '@tanstack/react-start/server'

import { ServerRoute as ApiUsersRouteImport } from './../../src/routes/api/users'

// Create/Update Routes

const rootRoute = createServerRoute()

const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-start/server' {
  interface FileRoutesByPath {
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Add type-safety to the createFileRoute function across the route tree

declare module './../../src/routes/api/users' {
  const createServerFileRoute: CreateServerFileRoute<
    FileRoutesByPath['/api/users']['parentRoute'],
    FileRoutesByPath['/api/users']['id'],
    FileRoutesByPath['/api/users']['path'],
    FileRoutesByPath['/api/users']['fullPath'],
    unknown
  >
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/api/users': typeof ApiUsersRoute
}

export interface FileRoutesByTo {
  '/api/users': typeof ApiUsersRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/api/users': typeof ApiUsersRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/api/users'
  fileRoutesByTo: FileRoutesByTo
  to: '/api/users'
  id: '__root__' | '/api/users'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ApiUsersRoute: typeof ApiUsersRoute
}

const rootRouteChildren: RootRouteChildren = {
  ApiUsersRoute: ApiUsersRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/api/users"
      ]
    },
    "/api/users": {
      "filePath": "api/users.ts"
    }
  }
}
ROUTE_MANIFEST_END */
